// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQwemVXnIcE4gvXM19t00wzDWc0riE5KE',
    appId: '1:49773168759:web:9859429929f4a53a669e72',
    messagingSenderId: '49773168759',
    projectId: 'flutter-coach-app',
    authDomain: 'flutter-coach-app.firebaseapp.com',
    storageBucket: 'flutter-coach-app.appspot.com',
    measurementId: 'G-XVHPC58502',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsTxahFh7dA_5Xcuvdk551ilxmi9zKLTc',
    appId: '1:49773168759:android:811466f61b5795a9669e72',
    messagingSenderId: '49773168759',
    projectId: 'flutter-coach-app',
    storageBucket: 'flutter-coach-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMlTtMHNJK_pc3EmvahCN5UWn0w20jOJM',
    appId: '1:49773168759:ios:5b8f2552740c8b87669e72',
    messagingSenderId: '49773168759',
    projectId: 'flutter-coach-app',
    storageBucket: 'flutter-coach-app.appspot.com',
    iosBundleId: 'com.example.flutterCoachApp',
  );
}
