// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKe8sfL7TqSF5T6EsEHpDeuztiHaiwtvI',
    appId: '1:759534976084:web:6e640ef4a89a9499ddc1c1',
    messagingSenderId: '759534976084',
    projectId: 'coachapp-59978',
    authDomain: 'coachapp-59978.firebaseapp.com',
    storageBucket: 'coachapp-59978.appspot.com',
    measurementId: 'G-NY7HG3KJLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_yg0_QQuBI7xi2H3hVXvN7O0pvt6YGxk',
    appId: '1:759534976084:android:d104fdce24dc5698ddc1c1',
    messagingSenderId: '759534976084',
    projectId: 'coachapp-59978',
    storageBucket: 'coachapp-59978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWcYh_a9SHGosQ5DPCs_sH138eRKgW8yE',
    appId: '1:759534976084:ios:566d75424b5a050eddc1c1',
    messagingSenderId: '759534976084',
    projectId: 'coachapp-59978',
    storageBucket: 'coachapp-59978.appspot.com',
    iosBundleId: 'com.example.flutterCoachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWcYh_a9SHGosQ5DPCs_sH138eRKgW8yE',
    appId: '1:759534976084:ios:8f7098e9999031b7ddc1c1',
    messagingSenderId: '759534976084',
    projectId: 'coachapp-59978',
    storageBucket: 'coachapp-59978.appspot.com',
    iosBundleId: 'com.example.flutterCoachApp.RunnerTests',
  );
}
